title: 小号的窝
author: 写文的小号
description: > # this means to ignore newlines until "baseurl:"
  这里是写文的小号！这个网站单纯就是拿来放我自己的文的，
  希望能够成为一个不会倒的粮仓！

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
